name: antiscam

on:
  issue_comment:
    types:
      - created
      - edited
  discussion_comment:
    types:
      - created
      - edited

permissions:
  pull-requests: write
  issues: write
  discussions: write

jobs:
  build:
    if: ${{ !github.event.issue.pull_request }}
    name: Antiscam
    runs-on: ubuntu-latest

    steps:
      - uses: vbaranov/antiscam-action@dev
        with:
          token: ${{ github.token }}
        env:
          whitelisted_logins: ${{ vars.SCAM_ACTION_WHITELISTED_LOGINS }}
